const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Mouse.Acts.RequestPointerLock,
		C3.Plugins.Mouse.Acts.ReleasePointerLock,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.OnLayoutStart
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{PlanoDeFundoEmBlocos: 0},
	{"8Direções": 0},
	{Hobbit: 0},
	{Mesasfudo: 0},
	{Teclado: 0},
	{Queijo: 0},
	{EstarDormindo: 0},
	{DofroTranquilo: 0},
	{PilhaEsquerda: 0},
	{CestoMeias: 0},
	{PilhaDireita: 0},
	{TipoMeia: 0},
	{ArrastarSoltar: 0},
	{MeiaSauron2: 0},
	{Toque: 0},
	{Mouse: 0},
	{TextoPontuacao: 0},
	{Partículas: 0},
	{Fumaca: 0},
	{FumacaCachimbo: 0},
	{BackgroundMeias1removebgpreview: 0},
	{BackgroundMeias3removebgpreview: 0},
	{BackgroundMeias2removebgpreview: 0},
	{BackgroundMeias4removebgpreview: 0},
	{MeiaArvoreGondorremovebgpreview: 0},
	{MeiaSauron: 0},
	{MeiaSauronremovebgpreview: 0},
	{MeiaLothlorien2removebgpreview: 0},
	{MeiaLothlorienremovebgpreview: 0},
	{MeiaArvoreGondor2removebgpreview: 0},
	{MeiaArvoreGondorremovebgpreview2: 0},
	{ProjetorDeSombra: 0},
	{MeiaUmAnel2removebgpreview: 0},
	{MeiaUmAnelremovebgpreview: 0},
	{MeiaHobbitHole: 0},
	{MeiaHobbitHoleremovebgpreview: 0},
	{QuadroTheShire: 0},
	{ferroada: 0},
	{Fixar: 0},
	{CajadoGandalfSFundo: 0},
	{Glamdring: 0},
	{TheOne: 0},
	{TheOne2: 0},
	{PontoAparicaoMeia: 0},
	{DofroAlgodeiroFalando: 0},
	{DofroAlgodeiroJoinha2: 0},
	{DofroDormindo: 0},
	{BolhaSono: 0},
	{texto_Gandalf: 0},
	{BG_Dialogo: 0},
	{Áudio: 0},
	{Luz: 0},
	{GandalfHat: 0},
	{TextoFerroada: 0},
	{TextoUmAnel: 0},
	{MeiaArrastadaUID: 0},
	{TempoInatividade: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Hobbit: class extends self.ISpriteInstance {},
	Mesasfudo: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Queijo: class extends self.ISpriteInstance {},
	DofroTranquilo: class extends self.ISpriteInstance {},
	PilhaEsquerda: class extends self.ISpriteInstance {},
	CestoMeias: class extends self.ISpriteInstance {},
	PilhaDireita: class extends self.ISpriteInstance {},
	MeiaSauron2: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	TextoPontuacao: class extends self.ITextInstance {},
	Partículas: class extends self.IParticlesInstance {},
	Fumaca: class extends self.ISpriteInstance {},
	FumacaCachimbo: class extends self.ISpriteInstance {},
	BackgroundMeias1removebgpreview: class extends self.ISpriteInstance {},
	BackgroundMeias3removebgpreview: class extends self.ISpriteInstance {},
	BackgroundMeias2removebgpreview: class extends self.ISpriteInstance {},
	BackgroundMeias4removebgpreview: class extends self.ISpriteInstance {},
	MeiaArvoreGondorremovebgpreview: class extends self.ISpriteInstance {},
	MeiaSauron: class extends self.ISpriteInstance {},
	MeiaSauronremovebgpreview: class extends self.ISpriteInstance {},
	MeiaLothlorien2removebgpreview: class extends self.ISpriteInstance {},
	MeiaLothlorienremovebgpreview: class extends self.ISpriteInstance {},
	MeiaArvoreGondor2removebgpreview: class extends self.ISpriteInstance {},
	MeiaArvoreGondorremovebgpreview2: class extends self.ISpriteInstance {},
	MeiaUmAnel2removebgpreview: class extends self.ISpriteInstance {},
	MeiaUmAnelremovebgpreview: class extends self.ISpriteInstance {},
	MeiaHobbitHole: class extends self.ISpriteInstance {},
	MeiaHobbitHoleremovebgpreview: class extends self.ISpriteInstance {},
	QuadroTheShire: class extends self.ISpriteInstance {},
	ferroada: class extends self.ISpriteInstance {},
	CajadoGandalfSFundo: class extends self.ISpriteInstance {},
	Glamdring: class extends self.ISpriteInstance {},
	TheOne: class extends self.ISpriteInstance {},
	TheOne2: class extends self.ISpriteInstance {},
	PontoAparicaoMeia: class extends self.ISpriteInstance {},
	DofroAlgodeiroFalando: class extends self.ISpriteInstance {},
	DofroAlgodeiroJoinha2: class extends self.ISpriteInstance {},
	DofroDormindo: class extends self.ISpriteInstance {},
	BolhaSono: class extends self.ISpriteInstance {},
	texto_Gandalf: class extends self.ITextInstance {},
	BG_Dialogo: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Luz: class extends self.ISpriteInstance {},
	GandalfHat: class extends self.ISpriteInstance {},
	TextoFerroada: class extends self.ITextInstance {},
	TextoUmAnel: class extends self.ITextInstance {}
}